ALTER TABLE `characters` ADD COLUMN `needs` varchar(255) NULL DEFAULT '{}' COLLATE 'utf8mb4_bin';
ALTER TABLE `characters` ADD COLUMN `UIposition` LONGTEXT NULL DEFAULT '{}' COLLATE 'utf8mb4_bin';

/* YOU NEED T OADD YOUR OWN ITEMS TO THE DATABSE WITH YOUR OWN LANGUAGE AND OPTIONS */